name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  MavenCentral:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          
      - name: Recovery GPG
        env:
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        run: |
          gpg --list-keys
          gpg --keyserver keyserver.ubuntu.com --recv-keys ${GPG_KEYNAME} && gpg --list-keys
          
      - name: Update .m2 settings.xml
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run:  echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\"><servers><server><id>ossrh</id><username>${OSSRH_USERNAME}</username><password>${OSSRH_PASSWORD}</password></server></servers><profiles><profile><id>ossrh</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.keyname>${GPG_KEYNAME}</gpg.keyname><gpg.passphrase>${GPG_PASSWORD}</gpg.passphrase></properties></profile></profiles></settings>" > $HOME/.m2/settings.xml

      - name: Publish package
        run: mvn clean deploy -Prelease -DprofileIdEnabled=true
